[package]
name = "openh264"
description = "Idiomatic bindings for OpenH264."
authors = ["Ralf Biedert <rb@xr.io>"]
keywords = ["multimedia", "encoding", "video"]
categories = ["api-bindings", "multimedia::video"]
version = "0.3.1"
edition = "2021"
rust-version = "1.65"
license = "BSD-2-Clause"
documentation = "https://docs.rs/openh264/"
repository = "https://github.com/ralfbiedert/openh264-rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["decoder", "encoder", "rayon"]
decoder = ["openh264-sys2/decoder"]
encoder = ["openh264-sys2/encoder"]
backtrace = [] # Remove once backtrace feature is stable.
rayon = ["dep:rayon"]

[dependencies]
openh264-sys2 = { path = "../openh264-sys2", version = "0.3.0", default-features = false }
rayon = { version = "1.6.1", optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dev-dependencies]
image = "0.24.4"
image-compare = "0.2.3"
